### ISSUE TITLE
some error about:"RuntimeError: cuda runtime error (100) : "

### ISSUE THREAD

**Issue by ysn7** [Cartus/AGGCN#22]
hello,when i run the " bash train_aggcn.sh",there are some errors.
but,i test my torch:
Default GPU Device: /device:GPU:0
Your tensorflow-gpu is available
Default GPU Device: Tesla P4
Your pytorch-gpu is available
and,my environment is 
cuda:10.1
python:3.7.5
pytorch:1.3.
could you please help me to solve this error?
thank you very much!

Finetune all embeddings.
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    trainer = GCNTrainer(opt, emb_matrix=emb_matrix)
  File "/home/yaoshengnan/AGGCN-master/semeval/model/trainer.py", line 68, in __init__
    self.model = GCNClassifier(opt, emb_matrix=emb_matrix)
  File "/home/yaoshengnan/AGGCN-master/semeval/model/aggcn.py", line 26, in __init__
    self.gcn_model = GCNRelationModel(opt, emb_matrix=emb_matrix)
  File "/home/yaoshengnan/AGGCN-master/semeval/model/aggcn.py", line 51, in __init__
    self.gcn = AGGCN(opt, embeddings)
  File "/home/yaoshengnan/AGGCN-master/semeval/model/aggcn.py", line 133, in __init__
    self.layers.append(GraphConvLayer(opt, self.mem_dim, self.sublayer_first))
  File "/home/yaoshengnan/AGGCN-master/semeval/model/aggcn.py", line 206, in __init__
    self.weight_list = self.weight_list.cuda()
  File "/root/anaconda3/envs/tf14/lib/python3.7/site-packages/torch/nn/modules/module.py", line 305, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/root/anaconda3/envs/tf14/lib/python3.7/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/tf14/lib/python3.7/site-packages/torch/nn/modules/module.py", line 224, in _apply
    param_applied = fn(param)
  File "/root/anaconda3/envs/tf14/lib/python3.7/site-packages/torch/nn/modules/module.py", line 305, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/root/anaconda3/envs/tf14/lib/python3.7/site-packages/torch/cuda/__init__.py", line 193, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:50

**Comment by ysn7** [comment]
pytorch=1.3.1

**Comment by ysn7** [comment]
thank you ,it has been solved

**Comment by amazingYX** [comment]
Hello, I have the same problem as you. Could you tell me how to solve it

**Comment by ZohaibRamzan** [comment]
> thank you ,it has been solved

Can you mention what was the problem?
